# Generated by Django 5.1.7 on 2025-05-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_bid_bidder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="thumbnail",
            field=models.ImageField(upload_to="fotos_coches/"),
        ),
    ]
