# Generated by Django 5.1.7 on 2025-05-11 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="price",
            new_name="start_price",
        ),
    ]
