# Generated by Django 5.1.7 on 2025-05-12 09:09

from django.db import migrations
from django.db import migrations, models

def add_price_column(apps, schema_editor):
    Auction = apps.get_model('auctions', 'Auction')
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE auctions_auction ADD COLUMN price DECIMAL(10, 2);
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.RunPython(add_price_column),
    ]
